extends:
  - google
  - plugin:prettier/recommended
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
rules:
  '@typescript-eslint/explicit-function-return-type':
    - error
    - allowExpressions: true
  '@typescript-eslint/no-object-literal-type-assertion': off
  '@typescript-eslint/indent':
    - error
    - 2
  prettier/prettier:
    - error
    - endOfLine: lf
      singleQuote: true
      trailingComma: all
  require-jsdoc: off

  # ToDo
  new-cap: 0
