extends:
  - google
  - plugin:prettier/recommended
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
rules:
  '@typescript-eslint/indent':
    - error
    - 2
  prettier/prettier:
    - error
    - singleQuote: true
      trailingComma: all
